### PR TITLE
Change Travis to use cvmfs and SL6

### PR DESCRIPTION
**Pull request by petricm**
Use a dockerized CERNVM to get the proper build environment and use cvmfs for dependencies.
The build is performed against HEAD install of iLCSoft which is produced approximately bi-weekly.

The current version of ROOT in this iLCSoft build is 6.08.00

### CODE REVIEW

**Comment by jstrube** [comment]
Thank you for preparing this patch.
We are not going to merge a pull request into master that breaks the build.
I have created the root-608 branch. Could you please re-open the pull request against that branch.

**Comment by petricm** [comment]
Sorry but I disagree with this. 
The aim of Continuous Integration is not to pass always, but that it indicates problems in software. The current state of LCFIPlus is that it does not compile under the constraints envisioned for the next release of iLCSoft, which is ROOT 6.08.00, and thus it is correct that the build fails. If I take iLCInstall and do HEAD/master it will fail. The master of LCFIPlus does not work with the masters of all other packages, subsequently the master build should fail.

The master branch should indicate the development direction (which is ROOT 6.08 and not 5.34.07), from which tags and branches for future releases are made, thus this test should remain in master, because it tests against master. And I think @gaede and @andresailer would agree with me that the most important think now is to make LCFIPlus build for the next release, and that it **does not build now**. Or in other words, we can only make a full release of iLCSoft once this tests really passes.

**Comment by gaede** [comment]
I absolutely agree with Marko - not fixing the build issues with ROOT 6.08.00 blocks us from including LCFIPlus in the patch release of ilcsoft that was planned for this week.
This PR should go into the master and the issue https://github.com/lcfiplus/LCFIPlus/issues/11 needs to be fixed.

**Comment by tomohikosan** [comment]
The ROOT 6.08 conflict should be resolved now, while at the same still keeping build with older versions of ROOT. Please confirm this with the ROOT build at DESY.

**Comment by gaede** [comment]
Thanks for fixing this Tomohiko. It works on DESY afs:
/afs/desy.de/project/ilcsoft/sw/x86_64_gcc48_sl6/HEAD-2016-11-10/LCFIPlus/HEAD/
( ignore the date, started this build yesterday).
I don't know why Travis fails - Marko, can you have a look ?

**Comment by petricm** [comment]
Can you restart the build in Travis please. I am not sure exactly why it fails, but the complaint that there is no TMVA/DataSetManager.h is strange because it's there.

**Comment by petricm** [comment]
I have rebased, to re-trigger the build. As you can see it was only a cvmfs/parrot/docker (something of them probably) glitch.

**Comment by gaede** [comment]
Ok great.
I also checked that the current master builds against ROOT 5.34 and 6.06.
Tomohiko, can you please create a release tag with the current master/HEAD ?
( or include the last commits in v00-06-04).

**Comment by tomohikosan** [comment]
Released new tag: v00-06-05

**Comment by jstrube** [comment]
I'm all for fixing this.
But we will not produce a master that is known not to build. That's what branches are for.
Thanks Marko for creating the patch to test against the new ROOT version and thanks Tomohiko for fixing this.

**Pull request merged**
